# Generated by Django 5.0 on 2023-12-21 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='filme.filme')),
            ],
        ),
    ]
